spring:
  application:
    name: ms-proceso-orquestador

  datasource:
    url: jdbc:mysql://localhost:3306/api-proceso?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "A12345$"

  rabbitmq:
    host: 192.168.18.39
    port: 5672
    username: guest
    password: guest

  amqp:
    deserialization:
      trust:
        all: true

saga:
  exchange: saga.exchange
  routing:
    create-proceso: proceso.create
    create-proceso-comite: proceso.comite.create
    delete-proceso: proceso.delete

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    enable: true
    path: /api/docs
  swagger-ui:
    enable: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
      health:
        show-details: always
